### ISSUE TITLE
  Redirect URI, html/index.html, does not use one of the allowed redirect protocols: http, https

### ISSUE THREAD

**Issue by aijcoa** [shimomo/laravel-ping#1]
I'm looping over some IPs from records in my DB, and after the 3rd record I get this error.

`Redirect URI, html/index.html, does not use one of the allowed redirect protocols: http, https`.

It works fine in local env, but not on prod with HTTPS. 

any ideas?

my code:

    foreach ($sim_ips as $ip) {
      if (($ip != "") && ($ip != "FAIL")) {
      	$health = Ping::check($ip);

        $sim = Sim::where('ip', $ip)->first();

        if($health == 200) {
      		$sim->status = 'online';
      	} else {
      		$sim->status = 'offline';
      	}

        $sim->save();
      }
    }

**Comment by shimomo** [comment]
Hi, I’m assuming you are using the [karlmonson/laravel-ping](https://github.com/karlmonson/laravel-ping).
Am I right?

**Comment by aijcoa** [comment]
@shimomo actually yes, my bad.
